http :
  host : "0.0.0.0"
  port : "8081"

papi-request :
  host : "0.0.0.0"
  port : "8082"
  basepath : "api"      
  path : "loan/status/update" 
  client_id : "0c5ff173846546a39c6080878a0915b0"  
  client_secret : "25eB4d4027bc4EC1Ad5A9DC5C36ceF2d"
  
  